const data = {
  products: [
    {
      name: 'Mũ đi biển fashion',
      slug: 'mu-di-bien',
      category: 'Mũ đi biển',
      image: '/images/mudibien1.jfif',
      isFeatured: true,
      featuredImage: '/images/banner3.jfif',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Mũ Phổ Biến',
    },
    {
      name: 'Mũ bảo hiểm',
      slug: 'mu-bao-hiem',
      category: 'Mũ bảo hiểm',
      image: '/images/mubaohiem1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.png',
      price: 80,
      brand: 'Royal',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Mũ Phổ Biến',
    },
    {
        name: 'Mũ chống dịch',
        slug: 'mu-chong-dich',
        category: 'Mũ chống dịch',
        image: '/images/muchondichtreem.jpg',
        isFeatured: true,
        featuredImage: '/images/banner1.png',
        price: 80,
        brand: 'Vital',
        rating: 4.2,
        numReviews: 10,
        countInStock: 20,
        description: 'Mũ Phổ Biến Mô tả sản phẩm mũ chống nắng, chắn bụi cho bé, nón cho bé chống giọt bắn, mũ người lớn Mũ trẻ em, mũ người lớn chất vải đẹp cao cấp, hàng đặt may, không phải hàng gia công, ngoài thị trường đang bán không dưới 150K',
      },

      {
        name: 'Mũ lưỡi chai',
        slug: 'mu-luoi-chai',
        category: 'Mũ lưỡi chai',
        image: '/images/muluoichai1.jpg',
        isFeatured: true,
        featuredImage: '/images/banner4.png',
        price: 80,
        brand: 'Rosy',
        rating: 4.2,
        numReviews: 10,
        countInStock: 20,
        description: 'Mũ Phổ Biến',
      },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/mubaohiem2.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Mũ Phổ Biến',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/mubaohiem3_4.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/muchongdich1.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/mudibien2.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};
export default data;
